---
# OSSEC installation questions
ossec_dir: /var/ossec
ossec_install_type: agent
ossec_email: y
ossec_email_address: inglevaibhav26@gmail.com
ossec_detected_smtp_use: n
ossec_smtp_server: localhost
ossec_integritycheck_daemon: y
ossec_rootkit_engine: y
ossec_active_response: y
ossec_firewalldrop_response: y
ansible_controller_ip: 192.168.1.1

- hosts: all
  sudo: true
  tasks:
     - name: Install Required Packages
       yum: name={{ item }} state=present
       with_items:
       - gcc 
       - inotify-tools
       - git
       - python-pip
       - pexpect
     
     - name: To download the tarball,
       get_url: 
          url:http://www.ossec.net/files/ossec-hids-2.8.2.tar.gz
          dest: /opt
     
       unarchive:
          src: /opt/ossec-hids-2.8.2.tar.gz
          command: mv ossec-hids-2.8.2.tar.gz ossec 
       
     - name: (OSSEC) Install OSSEC-HIDS in local mode
       expect:
          command: "/bin/bash /opt/ossec-hids/install.sh"
          timeout: 300
          responses:
             en/br: "en"
             Press ENTER: ""
             What kind of installation do you want: "{{ ossec_install_type }}"
             Choose where to install the OSSEC HIDS: "{{ ossec_dir }}"
             Do you want e-mail notification: "{{ ossec_email }}"
             e-mail address: "{{ ossec_email_address }}"
             Do you want to use it: "{{ ossec_detected_smtp_use }}"
             SMTP server ip: "{{ ossec_smtp_server }}"
             Do you want to run the integrity check daemon: "{{ ossec_integritycheck_daemon }}"
             Do you want to run the rootkit detection engine: "{{ ossec_rootkit_engine }}"
             Do you want to enable active response: "{{ ossec_active_response }}"
             Do you want to enable the firewall-drop response: "{{ ossec_firewalldrop_response }}"
             Do you want to add more IPs to the white list: "n"
          become: yes
          notify: restart ossec   
          
     - name: (OSSEC) Start OSSEC service
       service:
          name: ossec
          state: started

     - name: (OSSEC) Whitelist Ansible Controller IP address
       lineinfile:
          path: /var/ossec/etc/ossec.conf
          insertafter: '</white_list>'
          state: present
          line: "    <white_list>{{ ansible_controller_ip }}</white_list>"
